"use client";

import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { SessionProvider, signOut, useSession } from 'next-auth/react'
import Navigation from './components/Navigation';

const inter = Inter({ subsets: ['latin'] })

const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {

	return (
		<html lang="en">
			<body className={inter.className}>
				<SessionProvider>
					<Navigation />
					{children}
				</SessionProvider>
			</body>
		</html>
	)
}
